from agno.agent import Agent
from agno.models.groq import Groq
from agno.models.openai.chat import OpenAIChat
from agno.tools.shell import ShellTools
import json

def simple_agent(): 
    agent = Agent(
        name="Simple Agent",
        model = Groq(id="llama-3.3-70b-versatile")
    )

    agent.print_response("Tell me a Dad Joke")

def openai_agent():
    agent = Agent(
        name="simple OpenAi Agent",
        model=OpenAIChat(id="gpt-4o"),
        markdown=True
    )

    agent.print_response("Tell me a Dad Joke")


def automator_agent(command: str, ):
    agent = Agent(
        name="Automator Agent",
        model = Groq(id="llama-3.3-70b-versatile"),
        tools=[ShellTools()],
        system_message="""
        You are an automator agent. Anytime you are asked to download or generate data from a script 
        make sure you download it in specified folders in "temp" folder in current directory. Python scripts are to be stored in scripts folder. 
        Data generated by any script should be under data folder. If director exists, override it or create a new versioned folder in it.
        """,
        show_tool_calls=True
    )

    # agent.print_response(command)

    # Get the response from the agent
    response = agent.run(command)

    result = {
        "agent_response": response.to_json(),
        "command": command,
        "agent_name": agent.name
    }

    print("\nAPI Response:")
    print(json.dumps(result, indent=2))

    return result
